#! /bin/bash

#*****----- Workspaces -----*****
bspc monitor -d 1  2  3  4  5 6
#*****----- Window Gaps -----*****
bspc config gapless_monocle false
bspc config window_gap 2
#*****----- Window Borders -----*****
#bspc config focused_border_color "#46a5e9"
#bspc config normal_border_color "#0B0F10"
bspc config border_width 0
#bspc config active_border_color "#46a5e9"
#bspc config presel_feedback_color "#6272a4"
#*****----- Fix Pointer -----*****
xsetroot -cursor_name left_ptr &

bspc config split_ratio          0.5
#*****----- BSPWM Configs -----*****
bspc config focus_follows_pointer true
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
#*****----- I DONT KNOW WTF IS THIS FOR -----*****
bspc config single_monocle	     true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
bspc config borderless_monocle   true


# moving floating windows and resize them with mouse, hold alt key
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
#*****----- BSPWN Rules -----*****
bspc rule -a feh state=floating
bspc rule -a eog state=floating
bspc rule -a firefox center=true state=tiled
# bspc rule -a firefox desktop='^2' follow=on
#bspc rule -a TelegramDesktop state=floating follow=on rectangle=485x1000+0+0
bspc rule -a TelegramDesktop state=floating follow=off
bspc rule -a Pavucontrol follow=on state=floating rectangle=800x400+1030+635
bspc rule -a Nm-connection-editor follow=on state=floating rectangle=800x400+1030+635
#*****----- BSPWN Launches -----*****
sxhkd &
numlockx &
nitrogen --restore &
picom &
telegram-desktop -startintray &
flameshot &
alsa &

#setxkbmap -option grp:alt_shift_toggle us,ru &

~/.config/bspwm/polybar/launch.sh
